# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2460fa957afe1b36639065f35c929b632f789c8eb1b2e78b8f390db8d38b361f491fe27913759b94b009894fdce8702451e542fa05b677bb6bc61e1d3f4adfe

test:
  secret_key_base: fa1ea9f2e8fd04256743a1217a17697a36cabb3cab1da05d63d03aa032559d7900e967d1a84a1d748897cde78dc6a40d6a436e43b1e9f1f8f49f10575e8ac014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
